### PR TITLE
Add a 404 page, add a bunch of shit to index.html, add a hire page that does nothing, and a tac for the hire page.

### PR DESCRIPTION
**Pull request by plun1331**
ok hear me out it looks decent this time

### CODE REVIEW

**Comment by plun1331** [comment]
also links will open in new tabs now

**Comment by plun1331** [comment]
i made a form thing for people to hire you to code shit but it doesn't do shit rn because i cant do js

**Comment by plun1331** [comment]
https://plun1331.github.io/
if you want preview it here lol pls no sue

**Comment by DimBis** [comment]
Well it looks pretty good but there's bunch of scroll buttons

**Pull request merged**
